In [1]:
import numpy as np

In [2]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
array_of_numbers = np.arange(1,20) # last value is always exclusive
array_of_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
#req: create a simple array with 6 numbers 

In [6]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [7]:
x = np.arange(6)

x

array([0, 1, 2, 3, 4, 5])

In [ ]:
x --> single dimension , (x,y) ---> 2 dimensional , (x,y,z) ---> 3 dimensional

In [8]:
x.shape

(6,)

In [9]:
y = np.arange(6).reshape(2,3)

y

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
y.shape # 2 dimensional

(2, 3)

In [11]:
y = np.arange(6).reshape(2,4)
y

ValueError: cannot reshape array of size 6 into shape (2,4)

In [12]:
z = np.arange(12).reshape(2,3,2) # 2*3*2=12

z

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [13]:
z.shape # x,y

(2, 3, 2)

In [14]:
z = np.arange(12).reshape(6,2)

In [15]:
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
z.shape # x,y

(6, 2)